#!/usr/bin/env bash
#displays numbers for 1 to 100 with specific rules

#remember the fizzbuzz thingy we did in high school?
#yeah, this is it's shell version.this thing is just everywhere
#like Blackpink is in everyone's area (bad joke.....yolk)

num=1
while [ $num -le 100 ]; do
    if [ $((num % 5)) -eq 0 ] && [ $((num % 3)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((num % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((num % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$num"
    fi
    ((num++))
done
