#!/usr/bin/env bash
#display "Best School" ten times but hi fter the 9th iteration
words="Best School"
count=0
while [ $count -lt 10 ]; do
#checks for the 9th iteration
if [ $count -eq 8 ]; then
echo "Hi"
else
echo "$words"
fi
((count++))
done
