#!/usr/bin/env bash
#write a script that loops from 1 to 10
#display "bad luck" on the 4th iteration
#display "good luck" on the 8th iteration
#display "Best School" on every other iteration

count=0
while [ $count -lt 10 ]; do
if [ $count -eq 3 ]; then
echo "bad luck"
elif [ $count -eq 7 ]; then
echo "good luck"
else
echo "Best School"
fi
((count++))
done
